package domain

import "errors"

var (
	ErrCreditCardIDRequired              = errors.New("credit card id is required")
	ErrCreditCardUserIDRequired          = errors.New("credit card user id is required")
	ErrCreditCardNameRequired            = errors.New("credit card name is required")
	ErrCreditCardAccountIDRequired       = errors.New("credit card linked account id is required")
	ErrCreditCardLimitInvalid            = errors.New("credit card limit is invalid")
	ErrCreditCardClosingDayInvalid       = errors.New("credit card closing day is invalid")
	ErrCreditCardDueDayInvalid           = errors.New("credit card due day is invalid")
	ErrCreditCardInvalidStatus           = errors.New("credit card status is invalid")
	ErrCreditCardNotFound                = errors.New("credit card not found")
	ErrCreditCardAccountNotFound         = errors.New("credit card account not found")
	ErrCreditCardCategoryNotFound        = errors.New("credit card category not found")
	ErrCreditCardCategoryTypeMismatch    = errors.New("credit card category type mismatch")
	ErrCreditCardLimitExceeded           = errors.New("credit card limit exceeded")
	ErrPurchaseIDRequired                = errors.New("card purchase id is required")
	ErrPurchaseDescriptionRequired       = errors.New("card purchase description is required")
	ErrPurchaseAmountInvalid             = errors.New("card purchase amount is invalid")
	ErrPurchaseDateRequired              = errors.New("card purchase date is required")
	ErrPurchaseTypeInvalid               = errors.New("card purchase type is invalid")
	ErrPurchaseInstallmentCountInvalid   = errors.New("card purchase installment count is invalid")
	ErrPurchaseFirstInvoiceMonthRequired = errors.New("card purchase first invoice month is required")
	ErrPurchaseInvalidStatus             = errors.New("card purchase status is invalid")
	ErrPurchaseNotFound                  = errors.New("card purchase not found")
	ErrPurchaseInvoiceAlreadyPaid        = errors.New("card purchase invoice already paid")
	ErrInstallmentInvalid                = errors.New("card installment is invalid")
	ErrInvoiceIDRequired                 = errors.New("card invoice id is required")
	ErrInvoiceReferenceMonthRequired     = errors.New("card invoice reference month is required")
	ErrInvoiceDueAtRequired              = errors.New("card invoice due date is required")
	ErrInvoiceInvalidStatus              = errors.New("card invoice status is invalid")
	ErrInvoiceNotFound                   = errors.New("card invoice not found")
	ErrInvoiceAlreadyClosed              = errors.New("card invoice is already closed")
	ErrInvoiceAlreadyPaid                = errors.New("card invoice is already paid")
	ErrInvoiceNotPayable                 = errors.New("card invoice is not payable")
	ErrInvoiceAlreadyCanceled            = errors.New("card invoice is canceled")
)
